version: '3.8'
services:
  db:
    image: postgis/postgis:15-3.4
    container_name: postgis_db
    environment:
      POSTGRES_DB: cafes
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
    depends_on:
      - db

  frontend:
    build: ./app
    container_name: react_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  postgres_data:
